// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: magazzino.proto
// Protobuf Java Version: 4.29.3

package dispatcher;

/**
 * Protobuf type {@code dispatcher.Articolo}
 */
public final class Articolo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:dispatcher.Articolo)
    ArticoloOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Articolo.class.getName());
  }
  // Use Articolo.newBuilder() to construct.
  private Articolo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Articolo() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dispatcher.MagazzinoOuterClass.internal_static_dispatcher_Articolo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dispatcher.MagazzinoOuterClass.internal_static_dispatcher_Articolo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dispatcher.Articolo.class, dispatcher.Articolo.Builder.class);
  }

  public static final int VALORE_FIELD_NUMBER = 1;
  private long valore_ = 0L;
  /**
   * <code>int64 valore = 1;</code>
   * @return The valore.
   */
  @java.lang.Override
  public long getValore() {
    return valore_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (valore_ != 0L) {
      output.writeInt64(1, valore_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (valore_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, valore_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dispatcher.Articolo)) {
      return super.equals(obj);
    }
    dispatcher.Articolo other = (dispatcher.Articolo) obj;

    if (getValore()
        != other.getValore()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VALORE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getValore());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dispatcher.Articolo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dispatcher.Articolo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dispatcher.Articolo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dispatcher.Articolo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dispatcher.Articolo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dispatcher.Articolo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dispatcher.Articolo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dispatcher.Articolo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dispatcher.Articolo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dispatcher.Articolo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dispatcher.Articolo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dispatcher.Articolo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dispatcher.Articolo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dispatcher.Articolo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dispatcher.Articolo)
      dispatcher.ArticoloOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dispatcher.MagazzinoOuterClass.internal_static_dispatcher_Articolo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dispatcher.MagazzinoOuterClass.internal_static_dispatcher_Articolo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dispatcher.Articolo.class, dispatcher.Articolo.Builder.class);
    }

    // Construct using dispatcher.Articolo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      valore_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dispatcher.MagazzinoOuterClass.internal_static_dispatcher_Articolo_descriptor;
    }

    @java.lang.Override
    public dispatcher.Articolo getDefaultInstanceForType() {
      return dispatcher.Articolo.getDefaultInstance();
    }

    @java.lang.Override
    public dispatcher.Articolo build() {
      dispatcher.Articolo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dispatcher.Articolo buildPartial() {
      dispatcher.Articolo result = new dispatcher.Articolo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dispatcher.Articolo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.valore_ = valore_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dispatcher.Articolo) {
        return mergeFrom((dispatcher.Articolo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dispatcher.Articolo other) {
      if (other == dispatcher.Articolo.getDefaultInstance()) return this;
      if (other.getValore() != 0L) {
        setValore(other.getValore());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              valore_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long valore_ ;
    /**
     * <code>int64 valore = 1;</code>
     * @return The valore.
     */
    @java.lang.Override
    public long getValore() {
      return valore_;
    }
    /**
     * <code>int64 valore = 1;</code>
     * @param value The valore to set.
     * @return This builder for chaining.
     */
    public Builder setValore(long value) {

      valore_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 valore = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearValore() {
      bitField0_ = (bitField0_ & ~0x00000001);
      valore_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:dispatcher.Articolo)
  }

  // @@protoc_insertion_point(class_scope:dispatcher.Articolo)
  private static final dispatcher.Articolo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dispatcher.Articolo();
  }

  public static dispatcher.Articolo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Articolo>
      PARSER = new com.google.protobuf.AbstractParser<Articolo>() {
    @java.lang.Override
    public Articolo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Articolo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Articolo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dispatcher.Articolo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

