// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: magazzino.proto
// Protobuf Java Version: 4.29.3

package dispatcher;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dispatcher.Empty)
    com.google.protobuf.MessageOrBuilder {
}
