// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: magazzino.proto
// Protobuf Java Version: 4.29.3

package dispatcher;

public final class MagazzinoOuterClass {
  private MagazzinoOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      MagazzinoOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dispatcher_Articolo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dispatcher_Articolo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dispatcher_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dispatcher_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017magazzino.proto\022\ndispatcher\"\032\n\010Articol" +
      "o\022\016\n\006valore\030\001 \001(\003\"\007\n\005Empty2x\n\tMagazzino\022" +
      "5\n\010deposita\022\024.dispatcher.Articolo\032\021.disp" +
      "atcher.Empty\"\000\0224\n\007preleva\022\021.dispatcher.E" +
      "mpty\032\024.dispatcher.Articolo\"\000B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dispatcher_Articolo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dispatcher_Articolo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dispatcher_Articolo_descriptor,
        new java.lang.String[] { "Valore", });
    internal_static_dispatcher_Empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dispatcher_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dispatcher_Empty_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
